export type Area = "tecnologia" | "salud" | "diseno" | "administracion" | "ingenieria" | "arte" | "ciencias" | "social";

export const areas: Record<Area, { label: string; color: string; emoji: string; desc: string }> = {
  tecnologia: { label: "Tecnología", color: "var(--grape)", emoji: "💻", desc: "Software, datos, IA y sistemas." },
  salud: { label: "Salud", color: "var(--leaf)", emoji: "🩺", desc: "Cuidar y mejorar la vida humana." },
  diseno: { label: "Diseño", color: "var(--coral)", emoji: "🎨", desc: "Resolver con estética y función." },
  administracion: { label: "Administración", color: "var(--ink)", emoji: "📊", desc: "Liderar, planear y gestionar." },
  ingenieria: { label: "Ingeniería", color: "var(--grape)", emoji: "⚙️", desc: "Construir el mundo físico." },
  arte: { label: "Arte", color: "var(--coral)", emoji: "🎭", desc: "Expresión, cultura y creatividad." },
  ciencias: { label: "Ciencias", color: "var(--leaf)", emoji: "🔬", desc: "Descubrir cómo funciona el universo." },
  social: { label: "Ciencias sociales", color: "var(--sun)", emoji: "🧠", desc: "Entender a las personas y sociedades." },
};

export type Career = {
  slug: string;
  name: string;
  area: Area;
  what: string;
  field: string;
  salary: string;
  duration: string;
  universities: string[];
};

export const careers: Career[] = [
  { slug: "ingenieria-de-software", name: "Ingeniería de Software", area: "tecnologia",
    what: "Diseña, construye y mantiene aplicaciones, plataformas y sistemas digitales.",
    field: "Empresas tech, startups, banca, salud digital, freelance remoto.",
    salary: "COP 3.5M – 18M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "Universidad Nacional de Colombia", "EAFIT", "Javeriana", "ICESI"] },
  { slug: "ciencia-de-datos", name: "Ciencia de Datos", area: "tecnologia",
    what: "Extrae conocimiento de datos con estadística, programación y machine learning.",
    field: "Tech, banca, retail, salud, gobierno, startups.",
    salary: "COP 4M – 20M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "EAFIT", "Javeriana", "Universidad del Rosario"] },
  { slug: "ingenieria-de-sistemas", name: "Ingeniería de Sistemas", area: "tecnologia",
    what: "Diseña sistemas informáticos, redes y soluciones integrales de software.",
    field: "TI corporativa, consultoría, banca, telecomunicaciones.",
    salary: "COP 3M – 12M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Universidad de Antioquia", "UIS", "Distrital"] },
  { slug: "ciberseguridad", name: "Ciberseguridad", area: "tecnologia",
    what: "Protege sistemas, redes y datos de ataques y vulnerabilidades.",
    field: "Banca, gobierno, consultoría, empresas tecnológicas.",
    salary: "COP 5M – 22M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "EAFIT", "Javeriana"] },

  { slug: "medicina", name: "Medicina", area: "salud",
    what: "Diagnostica, trata y previene enfermedades para cuidar la salud de las personas.",
    field: "Hospitales, clínicas, investigación, salud pública, consulta privada.",
    salary: "COP 4M – 18M / mes", duration: "6 años + especialidad",
    universities: ["Universidad Nacional", "Universidad de Antioquia", "Javeriana", "Universidad del Rosario", "UIS"] },
  { slug: "enfermeria", name: "Enfermería", area: "salud",
    what: "Cuida y acompaña a pacientes, administra tratamientos y educa en salud.",
    field: "Hospitales, clínicas, atención domiciliaria, salud pública.",
    salary: "COP 2.5M – 6M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Universidad de Antioquia", "Javeriana", "CES"] },
  { slug: "odontologia", name: "Odontología", area: "salud",
    what: "Previene, diagnostica y trata enfermedades bucales y dentales.",
    field: "Consulta privada, clínicas, EPS, docencia.",
    salary: "COP 3M – 12M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "CES", "Javeriana", "Universidad de Cartagena"] },
  { slug: "psicologia", name: "Psicología", area: "social",
    what: "Estudia el comportamiento y la mente para acompañar procesos clínicos, educativos u organizacionales.",
    field: "Consulta clínica, RR.HH., educación, investigación.",
    salary: "COP 2.5M – 8M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Javeriana", "Universidad de los Andes", "Konrad Lorenz"] },

  { slug: "diseno-grafico", name: "Diseño Gráfico", area: "diseno",
    what: "Comunica ideas a través de imagen, tipografía e identidad visual.",
    field: "Agencias, estudios, in-house, freelance, publicidad y editorial.",
    salary: "COP 2M – 8M / mes", duration: "4–5 años",
    universities: ["Universidad Nacional", "Javeriana", "Jorge Tadeo Lozano", "Universidad de Caldas"] },
  { slug: "diseno-industrial", name: "Diseño Industrial", area: "diseno",
    what: "Diseña productos físicos integrando función, estética y producción.",
    field: "Manufactura, consumo, automotriz, mobiliario, emprendimiento.",
    salary: "COP 2.5M – 8M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Javeriana", "Universidad de los Andes", "Jorge Tadeo Lozano"] },
  { slug: "diseno-ux-ui", name: "Diseño UX/UI", area: "diseno",
    what: "Diseña experiencias digitales centradas en el usuario, web y apps.",
    field: "Startups, tech, agencias digitales, banca, freelance.",
    salary: "COP 3.5M – 14M / mes", duration: "4 años",
    universities: ["Jorge Tadeo Lozano", "Universidad de los Andes", "EAFIT", "Universidad del Valle"] },

  { slug: "administracion-de-empresas", name: "Administración de Empresas", area: "administracion",
    what: "Planea, dirige y optimiza organizaciones en finanzas, marketing y operaciones.",
    field: "Corporativos, consultoría, banca, emprendimiento, ONGs.",
    salary: "COP 3M – 15M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "EAFIT", "Externado", "Javeriana", "ICESI"] },
  { slug: "economia", name: "Economía", area: "administracion",
    what: "Analiza cómo se producen, distribuyen y consumen bienes y servicios.",
    field: "Banca, gobierno, consultoría, investigación, finanzas.",
    salary: "COP 3.5M – 16M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "Universidad Nacional", "Externado", "Universidad del Rosario"] },
  { slug: "contaduria", name: "Contaduría Pública", area: "administracion",
    what: "Registra, audita y reporta la información financiera de organizaciones.",
    field: "Auditoría, banca, sector público, firmas Big Four.",
    salary: "COP 2.5M – 12M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Universidad de Antioquia", "Externado", "Jorge Tadeo Lozano"] },
  { slug: "mercadeo", name: "Mercadeo", area: "administracion",
    what: "Crea estrategias para conectar productos y marcas con sus audiencias.",
    field: "Agencias, marcas, retail, tech, emprendimiento.",
    salary: "COP 2.5M – 12M / mes", duration: "4–5 años",
    universities: ["EAFIT", "CESA", "ICESI", "Jorge Tadeo Lozano"] },

  { slug: "ingenieria-civil", name: "Ingeniería Civil", area: "ingenieria",
    what: "Diseña y construye infraestructura: edificios, puentes, carreteras y obras hidráulicas.",
    field: "Constructoras, gobierno, consultoría, desarrollo inmobiliario.",
    salary: "COP 3M – 12M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "UIS", "Escuela Colombiana de Ingeniería", "EAFIT"] },
  { slug: "ingenieria-mecanica", name: "Ingeniería Mecánica", area: "ingenieria",
    what: "Diseña máquinas, sistemas térmicos y procesos de manufactura.",
    field: "Manufactura, automotriz, energía, oil & gas.",
    salary: "COP 3.5M – 14M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "UIS", "Universidad de los Andes", "EAFIT"] },
  { slug: "ingenieria-industrial", name: "Ingeniería Industrial", area: "ingenieria",
    what: "Optimiza procesos, cadenas de suministro y operaciones en organizaciones.",
    field: "Manufactura, logística, consultoría, retail, tech.",
    salary: "COP 3M – 14M / mes", duration: "5 años",
    universities: ["Universidad de los Andes", "Universidad Nacional", "Javeriana", "ICESI"] },
  { slug: "arquitectura", name: "Arquitectura", area: "ingenieria",
    what: "Diseña espacios habitables y urbanos integrando estética, técnica y sostenibilidad.",
    field: "Estudios, desarrollo urbano, gobierno, obra propia.",
    salary: "COP 2.5M – 10M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Javeriana", "Universidad de los Andes", "Jorge Tadeo Lozano"] },

  { slug: "artes-visuales", name: "Artes Visuales", area: "arte",
    what: "Crea obra artística (pintura, escultura, instalación, video) y participa del circuito cultural.",
    field: "Galerías, museos, gestión cultural, docencia, freelance.",
    salary: "Variable — proyectos y comisiones", duration: "5 años",
    universities: ["Universidad Nacional", "Universidad de los Andes", "Javeriana"] },
  { slug: "musica", name: "Música", area: "arte",
    what: "Interpreta, compone, produce o investiga música en distintos géneros y formatos.",
    field: "Producción, conciertos, educación, audiovisual, freelance.",
    salary: "Variable — proyectos y giras", duration: "5 años",
    universities: ["Universidad Nacional", "Javeriana", "EAFIT", "Universidad de Antioquia"] },
  { slug: "cine-y-television", name: "Cine y Televisión", area: "arte",
    what: "Crea contenidos audiovisuales: dirección, guion, fotografía, montaje.",
    field: "Productoras, streaming, publicidad, contenido digital.",
    salary: "COP 2M – 10M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Jorge Tadeo Lozano", "Politécnico Grancolombiano"] },

  { slug: "biologia", name: "Biología", area: "ciencias",
    what: "Investiga los seres vivos y los ecosistemas; aporta a salud, conservación y biotech.",
    field: "Investigación, laboratorios, conservación, docencia.",
    salary: "COP 2.5M – 7M / mes", duration: "5 años",
    universities: ["Universidad Nacional", "Universidad de los Andes", "Universidad de Antioquia"] },
];

// 20 universidades de Colombia
export const universities = [
  { name: "Universidad Nacional de Colombia", country: "Colombia", modality: "Presencial", cost: "Pública — matrícula según estrato", programs: 95 },
  { name: "Universidad de los Andes", country: "Colombia", modality: "Presencial", cost: "COP 14M–22M / semestre", programs: 80 },
  { name: "Pontificia Universidad Javeriana", country: "Colombia", modality: "Presencial / Híbrida", cost: "COP 12M–20M / semestre", programs: 75 },
  { name: "Universidad de Antioquia", country: "Colombia", modality: "Presencial", cost: "Pública — gratuita / baja matrícula", programs: 85 },
  { name: "EAFIT", country: "Colombia", modality: "Presencial / Híbrida", cost: "COP 11M–17M / semestre", programs: 55 },
  { name: "ICESI", country: "Colombia", modality: "Presencial", cost: "COP 10M–15M / semestre", programs: 45 },
  { name: "Universidad del Rosario", country: "Colombia", modality: "Presencial", cost: "COP 11M–18M / semestre", programs: 50 },
  { name: "Universidad Externado de Colombia", country: "Colombia", modality: "Presencial", cost: "COP 9M–15M / semestre", programs: 50 },
  { name: "Universidad del Valle", country: "Colombia", modality: "Presencial", cost: "Pública — baja matrícula", programs: 90 },
  { name: "Universidad Industrial de Santander (UIS)", country: "Colombia", modality: "Presencial", cost: "Pública — baja matrícula", programs: 70 },
  { name: "Universidad del Norte", country: "Colombia", modality: "Presencial", cost: "COP 10M–16M / semestre", programs: 60 },
  { name: "Jorge Tadeo Lozano", country: "Colombia", modality: "Presencial", cost: "COP 7M–12M / semestre", programs: 55 },
  { name: "CES", country: "Colombia", modality: "Presencial", cost: "COP 10M–15M / semestre", programs: 30 },
  { name: "CESA", country: "Colombia", modality: "Presencial", cost: "COP 12M–17M / semestre", programs: 8 },
  { name: "Universidad de La Sabana", country: "Colombia", modality: "Presencial", cost: "COP 10M–16M / semestre", programs: 40 },
  { name: "Escuela Colombiana de Ingeniería Julio Garavito", country: "Colombia", modality: "Presencial", cost: "COP 9M–13M / semestre", programs: 25 },
  { name: "Universidad de Cartagena", country: "Colombia", modality: "Presencial", cost: "Pública — baja matrícula", programs: 50 },
  { name: "Universidad Distrital Francisco José de Caldas", country: "Colombia", modality: "Presencial", cost: "Pública — gratuita / baja", programs: 65 },
  { name: "Universidad Pedagógica Nacional", country: "Colombia", modality: "Presencial", cost: "Pública — baja matrícula", programs: 35 },
  { name: "Politécnico Grancolombiano", country: "Colombia", modality: "Virtual / Presencial", cost: "COP 3M–7M / semestre", programs: 60 },
];
